import { ENZYME_QUIZ_EXERCISES } from "./enzymeQuizExercises.js";

/** Ch 4 Enzymes — concept checks from course notes (MCQ answer key aligned). */
export const QUIZ_SECTIONS = [
  { id: "enzyme-basics", label: "Enzymes & active sites", labelZh: "酶與活性位點" },
  { id: "mechanism", label: "Enzyme mechanism", labelZh: "酶的作用機制" },
  { id: "factors", label: "Factors affecting activity", labelZh: "影響酶活性的因素" },
  { id: "denaturation", label: "Denaturation", labelZh: "變性" },
];

export const ENZYME_QUIZ = [
  {
    id: "enz-1",
    section: "enzyme-basics",
    difficulty: "Foundation",
    stem: "What is the primary role of enzymes in biological reactions?",
    options: [
      { key: "A", text: "Increase the energy needed for a reaction" },
      { key: "B", text: "Provide energy for a reaction" },
      { key: "C", text: "Lower the activation energy of a reaction" },
      { key: "D", text: "Convert products into substrates" },
    ],
    answer: "C",
    hint: "Enzymes are catalysts — they lower activation energy so reactions proceed faster.",
  },
  {
    id: "enz-2",
    section: "enzyme-basics",
    difficulty: "Foundation",
    stem: "Which of the following is true about enzymes?",
    options: [
      { key: "A", text: "They are consumed in a reaction" },
      { key: "B", text: "They remain unchanged after a reaction" },
      { key: "C", text: "They increase the activation energy of a reaction" },
      { key: "D", text: "They only work at high temperatures" },
    ],
    answer: "B",
    hint: "Catalysts are not used up — the enzyme is released unchanged after products form.",
  },
  {
    id: "enz-3",
    section: "mechanism",
    difficulty: "Foundation",
    stem: "What is the substrate for the enzyme maltase?",
    options: [
      { key: "A", text: "Glucose" },
      { key: "B", text: "Maltose" },
      { key: "C", text: "Water" },
      { key: "D", text: "Starch" },
    ],
    answer: "B",
    hint: "Maltase hydrolyses maltose into two glucose molecules.",
  },
  {
    id: "enz-4",
    section: "mechanism",
    difficulty: "Foundation",
    stem: "What are the products of the enzymatic breakdown of maltose?",
    options: [
      { key: "A", text: "Glucose and water" },
      { key: "B", text: "Maltase and water" },
      { key: "C", text: "Two glucose molecules" },
      { key: "D", text: "Starch and water" },
    ],
    answer: "C",
    hint: "Maltose + water → glucose + glucose (hydrolysis catalysed by maltase).",
  },
  {
    id: "enz-5",
    section: "enzyme-basics",
    difficulty: "Foundation",
    stem: "Which statement best describes the active site of an enzyme?",
    options: [
      { key: "A", text: "It is a random region on the enzyme" },
      { key: "B", text: "It has a specific shape complementary to the substrate" },
      { key: "C", text: "It is destroyed after each reaction" },
      { key: "D", text: "It binds to any molecule" },
    ],
    answer: "B",
    hint: "Lock-and-key / induced fit — the active site matches the substrate shape.",
  },
  {
    id: "enz-6",
    section: "enzyme-basics",
    difficulty: "Foundation",
    stem: "What happens to the enzyme after releasing the products?",
    options: [
      { key: "A", text: "It is denatured" },
      { key: "B", text: "It remains unchanged" },
      { key: "C", text: "It is consumed in the reaction" },
      { key: "D", text: "It becomes inactive permanently" },
    ],
    answer: "B",
    hint: "The enzyme is free to bind another substrate molecule.",
  },
  {
    id: "enz-7",
    section: "denaturation",
    difficulty: "Standard",
    stem: "What happens to an enzyme if the temperature exceeds its optimum?",
    options: [
      { key: "A", text: "It becomes more active" },
      { key: "B", text: "Its active site changes shape, leading to denaturation" },
      { key: "C", text: "It binds to more substrates" },
      { key: "D", text: "It stops functioning temporarily but recovers" },
    ],
    answer: "B",
    hint: "High temperature disrupts hydrogen bonds holding the 3D structure.",
  },
  {
    id: "enz-8",
    section: "factors",
    difficulty: "Foundation",
    stem: "Which of the following factors does NOT affect enzyme activity?",
    options: [
      { key: "A", text: "Temperature" },
      { key: "B", text: "Substrate concentration" },
      { key: "C", text: "Enzyme concentration" },
      { key: "D", text: "Light intensity" },
    ],
    answer: "D",
    hint: "Temperature and concentrations affect collision rate and active-site occupancy.",
  },
  {
    id: "enz-9",
    section: "factors",
    difficulty: "Standard",
    stem: "How does increasing substrate concentration affect enzymatic activity?",
    options: [
      { key: "A", text: "It always increases the rate of reaction" },
      { key: "B", text: "It increases the rate of reaction until all active sites are occupied" },
      { key: "C", text: "It decreases the rate of reaction" },
      { key: "D", text: "It has no effect on the rate of reaction" },
    ],
    answer: "B",
    hint: "Rate rises with more substrate until saturation — then it plateaus.",
  },
  {
    id: "enz-10",
    section: "factors",
    difficulty: "Foundation",
    stem: "What happens to enzyme activity at low temperatures?",
    options: [
      { key: "A", text: "It increases due to high collision frequency" },
      { key: "B", text: "It decreases due to low kinetic energy of molecules" },
      { key: "C", text: "It remains unchanged" },
      { key: "D", text: "The enzyme denatures" },
    ],
    answer: "B",
    hint: "Low temperature means slow molecular movement and fewer successful collisions.",
  },
  {
    id: "enz-11",
    section: "denaturation",
    difficulty: "Foundation",
    stem: "What is the effect of boiling on enzymes?",
    options: [
      { key: "A", text: "Enzymes become more efficient" },
      { key: "B", text: "Enzymes denature and lose their function" },
      { key: "C", text: "Enzymes bind more strongly to substrates" },
      { key: "D", text: "Enzymes become inactive temporarily" },
    ],
    answer: "B",
    hint: "Boiling destroys the specific 3D conformation of the active site.",
  },
  {
    id: "enz-12",
    section: "mechanism",
    difficulty: "Foundation",
    stem: "Which of the following is true about enzyme-substrate complexes?",
    options: [
      { key: "A", text: "They form randomly without specific binding" },
      { key: "B", text: "They lower the activation energy of the reaction" },
      { key: "C", text: "They increase the activation energy of the reaction" },
      { key: "D", text: "They are consumed during the reaction" },
    ],
    answer: "B",
    hint: "The ES complex is the transition state where activation energy is reduced.",
  },
  {
    id: "enz-13",
    section: "mechanism",
    difficulty: "Standard",
    stem: "What is the function of catalase in the reaction with hydrogen peroxide?",
    options: [
      { key: "A", text: "Breaks down hydrogen peroxide into oxygen and glucose" },
      { key: "B", text: "Breaks down hydrogen peroxide into water and oxygen" },
      { key: "C", text: "Combines hydrogen peroxide with water" },
      { key: "D", text: "Converts hydrogen peroxide into starch" },
    ],
    answer: "B",
    hint: "Catalase decomposes H₂O₂ into H₂O and O₂.",
  },
  {
    id: "enz-14",
    section: "factors",
    difficulty: "Standard",
    stem: "What happens when enzyme concentration is increased, assuming substrate concentration is constant?",
    options: [
      { key: "A", text: "Reaction rate decreases" },
      { key: "B", text: "Reaction rate increases until all substrates are used" },
      { key: "C", text: "Reaction rate remains constant" },
      { key: "D", text: "Enzyme denaturation occurs" },
    ],
    answer: "B",
    hint: "More enzyme molecules mean more active sites available to bind substrate.",
  },
  {
    id: "enz-15",
    section: "factors",
    difficulty: "Foundation",
    stem: "What is the optimum temperature for most enzymes in the human body?",
    options: [
      { key: "A", text: "25°C" },
      { key: "B", text: "37°C" },
      { key: "C", text: "50°C" },
      { key: "D", text: "60°C" },
    ],
    answer: "B",
    hint: "Human body temperature is about 37°C — enzymes work best near this.",
  },
  {
    id: "enz-16",
    section: "denaturation",
    difficulty: "Standard",
    stem: "Which of the following best describes enzyme denaturation?",
    options: [
      { key: "A", text: "Irreversible loss of the enzyme's specific 3D structure" },
      { key: "B", text: "Temporary inactivation of the enzyme" },
      { key: "C", text: "Increased enzyme activity" },
      { key: "D", text: "A reversible process" },
    ],
    answer: "A",
    hint: "Denaturation changes the active-site shape — often permanently.",
  },
  {
    id: "enz-17",
    section: "denaturation",
    difficulty: "Standard",
    stem: "What happens to the enzyme-substrate complex when the enzyme is denatured?",
    options: [
      { key: "A", text: "It forms faster" },
      { key: "B", text: "It cannot form" },
      { key: "C", text: "It remains unaffected" },
      { key: "D", text: "It forms but does not release products" },
    ],
    answer: "B",
    hint: "Without the correct active-site shape, substrate cannot bind specifically.",
  },
  {
    id: "enz-18",
    section: "factors",
    difficulty: "Foundation",
    stem: "Which of the following factors increases the chance of forming enzyme-substrate complexes?",
    options: [
      { key: "A", text: "Low enzyme concentration" },
      { key: "B", text: "Low substrate concentration" },
      { key: "C", text: "Higher collision frequency" },
      { key: "D", text: "Denaturation" },
    ],
    answer: "C",
    hint: "More collisions between enzyme and substrate raise the chance of binding.",
  },
  {
    id: "enz-19",
    section: "mechanism",
    difficulty: "Standard",
    stem: "What is the role of water in the enzymatic breakdown of maltose?",
    options: [
      { key: "A", text: "It is a product of the reaction" },
      { key: "B", text: "It is a substrate that participates in the reaction" },
      { key: "C", text: "It denatures the enzyme" },
      { key: "D", text: "It has no role in the reaction" },
    ],
    answer: "B",
    hint: "Hydrolysis requires water — it is used to split the glycosidic bond.",
  },
  {
    id: "enz-20",
    section: "enzyme-basics",
    difficulty: "Foundation",
    stem: "Which of the following is a characteristic of enzymes?",
    options: [
      { key: "A", text: "They are effective at all temperatures" },
      { key: "B", text: "They are specific to their substrates" },
      { key: "C", text: "They require light for activation" },
      { key: "D", text: "They are consumed during reactions" },
    ],
    answer: "B",
    hint: "Enzyme specificity comes from the shape of the active site.",
  },
  ...ENZYME_QUIZ_EXERCISES,
];
